### PR TITLE
Removing cwt to its own package

### PR DESCRIPTION
**Pull request by dsweber2**
In the interest of not pestering you all the time with updates to the continuous wavelet transform, I split it out into a separate package [here](https://github.com/dsweber2/ContinuousWavelets.jl) (longterm home is likely [here](https://github.com/UCD4IDS/ContinuousWavelets.jl)). As I'm planning on adding ContinuousWavelets to the registry, its time for the type piracy to end. This pull request is just to remove what I'd added and add a brief link to ContinuousWavelets.jl in the readme. It appears that some others have done a similar thing with [WaveletsExt.jl](https://github.com/UCD4IDS/WaveletsExt.jl) for a variety of other extensions, so I added a bit in the readme pointing to both of these packages. Hopefully this doesn't result in too much of a headache for others who want to use these codes.

### CODE REVIEW

**Comment by gummif** [comment]
Thanks for that, I didn't know about these extensions. I will probably wait for the other package to be stable and usable, and then merge this in as a major release to not break anything.

**Comment by dsweber2** [comment]
ContinuousWavelets has been added to the registry and has all tests passed. If it moves from the [UCD4IS link](https://github.com/UCD4IDS/ContinuousWavelets.jl) I'll make sure to come back here and update the link.

**Comment by dsweber2** [comment]
The continued presence of `cwt` in Wavelets.jl means that users frequently get warnings about the function being overwritten. the cwt/icwt are both stable over there, so I would appreciate if you could merge this.

**Comment by JeffFessler** [comment]
Hi, I am just a minor contributor here, not a maintainer, but I would like to suggest that it might be preferable to house related wavelet packages under https://github.com/JuliaDSP to aid discoverability and perhaps even long-term maintenance.  I am not a maintainer there either (and perhaps the list of maintainers there is disconcertingly small for a topic as broad as DSP).  Nevertheless, there is an email list there so you could contact them and see if they will let you join the org and house your wavelet packages there.  The PR looks reasonable to me btw.

**Pull request merged**
